/**
 * Valo API.
 *
 * Small on purpose: the catalogue is static data generated by scripts/ingest.mjs
 * and scripts/media.mjs, and the only write path is a quote request. In
 * production this process also serves the built web app.
 */
import { createServer } from 'node:http'
import { readFile, appendFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import express from 'express'
import compression from 'compression'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const PORT = Number(process.env.PORT ?? 8787)
const DATA = join(ROOT, 'data')
const INQUIRIES = join(DATA, 'inquiries.jsonl')
const WEB_DIST = join(ROOT, 'apps/web/dist')

const catalog = JSON.parse(await readFile(join(DATA, 'catalog.json'), 'utf8'))

const app = express()
app.disable('x-powered-by')
app.use(compression())
app.use(express.json({ limit: '32kb' }))

const api = express.Router()

api.get('/health', (_req, res) => {
  res.json({ ok: true, pieces: catalog.products.length, generatedAt: catalog.generatedAt })
})

api.get('/catalog', (_req, res) => {
  res.json({ collections: catalog.collections, hero: catalog.hero, products: catalog.products })
})

api.get('/collections', (_req, res) => {
  res.json(catalog.collections)
})

api.get('/products', (req, res) => {
  const { collection, q } = req.query
  let list = catalog.products
  if (collection) list = list.filter((p) => p.collection === collection)
  if (q) {
    const needle = String(q).toLowerCase()
    list = list.filter((p) => p.name.toLowerCase().includes(needle))
  }
  res.json(list)
})

api.get('/products/:slug', (req, res) => {
  const product = catalog.products.find((p) => p.slug === req.params.slug)
  if (!product) return res.status(404).json({ error: 'not_found' })
  res.json(product)
})

/** Naive per-IP throttle: enough to keep a bored bot from filling the file. */
const recent = new Map()
const WINDOW_MS = 60_000
const MAX_PER_WINDOW = 5

function throttled(ip) {
  const now = Date.now()
  const hits = (recent.get(ip) ?? []).filter((t) => now - t < WINDOW_MS)
  hits.push(now)
  recent.set(ip, hits)
  return hits.length > MAX_PER_WINDOW
}

const isEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value)
const trim = (value, max) => String(value ?? '').trim().slice(0, max)

api.post('/inquiries', async (req, res) => {
  const ip = req.ip ?? 'unknown'
  if (throttled(ip)) return res.status(429).json({ error: 'too_many_requests' })

  const inquiry = {
    name: trim(req.body?.name, 120),
    email: trim(req.body?.email, 160),
    phone: trim(req.body?.phone, 40),
    piece: trim(req.body?.piece, 160),
    message: trim(req.body?.message, 4000),
  }

  const errors = []
  if (!inquiry.name) errors.push('name')
  if (!isEmail(inquiry.email)) errors.push('email')
  if (!inquiry.message) errors.push('message')
  if (errors.length) return res.status(422).json({ error: 'invalid', fields: errors })

  await mkdir(DATA, { recursive: true })
  await appendFile(
    INQUIRIES,
    `${JSON.stringify({ ...inquiry, receivedAt: new Date().toISOString(), ip })}\n`,
    'utf8',
  )

  res.status(201).json({ ok: true })
})

app.use('/api', api)

// Production: serve the built SPA. In development Vite does this and proxies /api.
if (existsSync(WEB_DIST)) {
  app.use(
    express.static(WEB_DIST, {
      setHeaders(res, path) {
        if (path.includes('/media/') || path.includes('/assets/')) {
          res.setHeader('cache-control', 'public, max-age=31536000, immutable')
        }
      },
    }),
  )
  app.get(/.*/, (_req, res) => res.sendFile(join(WEB_DIST, 'index.html')))
}

createServer(app).listen(PORT, () => {
  console.log(`valo api  →  http://localhost:${PORT}  (${catalog.products.length} pieces)`)
})
